### ISSUE TITLE
bootstrap's creation of client.rb should mimic chef gem's code

### ISSUE THREAD

**Issue by jeremiahsnapp** [chef/knife-windows#133] opened 2014-12-08 15:20 UTC
The code that creates the client.rb config during bootstrap should manage the same options that chef gem's code does.

Now that Chef Client 12 is out and SSL verification is enabled by default the knife-windows' code should auto-transfer `trusted_certs_dir` and manage `verify_api_cert` and `ssl_verify_mode`.

https://github.com/opscode/knife-windows/blob/0.8.2/lib/chef/knife/core/windows_bootstrap_context.rb#L47-L80

https://github.com/opscode/chef/blob/12.0.0/lib/chef/knife/core/bootstrap_context.rb#L56-L116

**Comment by carpnick** [comment] 2015-01-08 03:17
So is this closed/completed or being left open until released?

**Comment by adamedx** [comment] 2015-01-08 07:37
@carpnick, we'll keep this open to track getting it released -- that way it's clear when someone encounters it that the issue is still active in the released gem.

**Comment by NimishaS** [comment] 2015-01-08 08:00
@carpnick , fix is merged in master branch but not released yet. We can close this issue once the fix is released.

**Comment by pburkholder** [comment] 2015-01-15 18:51
@adamedx Any blockers to releasing 0.8.3 or 0.8.3.rc for this?

**Comment by adamedx** [comment] 2015-01-15 18:53
No, working on an RC release today, would be great to confirm this resolves all the issues once the rc is out.

**Comment by adamedx** [comment] 2015-01-16 19:07
We've uncovered some RC release blockers, so we won't have the release today. You can still try out master @carpnick / @pburkholder , but one some systems the removal of the event-machine dependency is causing non-deterministic behavior which we need to address before we have a usable RC.

If we can't fix this soon enough in master, the option will be to backport the SSL changes to a stable branch and release a patch.

**Comment by kwilczynski** [comment] 2015-01-16 23:27
@adamedx @NimishaS do y'all know when this will be resolved and when a new release would be cut? We have a customer (actually, more than one) who is blocked by this, and would like to see this fixed before they go live in production.

**Comment by adamedx** [comment] 2015-01-30 06:58
@btm, time to pull trigger on 0.8.3 -- that will fix the issue for users with chef-client 11.

**Comment by btm** [comment] 2015-02-10 20:30
@jeremiahsnapp 0.8.4.rc.0 should contain this fix now. could you please test it?

**Comment by btm** [comment] 2015-02-12 19:17
the following options aren't fully implemented still
    --bootstrap-template
    --[no-]node-verify-api-cert
    --node-ssl-verify-mode

I've copied over --node-ssl-verify-mode and --node-verify-api-cert and released 0.8.4.r.c1.

I skipped bootstrap-template because there was more than just copying the option, and we'd like to look at use cases for using different templates versus just a different URL. maybe we need a specific issue to collect that.

**Comment by NimishaS** [comment] 2015-02-13 05:18
Pr- https://github.com/chef/knife-windows/pull/189 and https://github.com/chef/knife-windows/pull/188 have some of the required changes.

**Comment by btm** [comment] 2015-02-13 18:25
--node-verify-api-cert and --node-ssl-verify-mode went out yesterday in 0.8.4.rc.1 via 65441013857d2d6d624280a01bb919a74df5466b.

20ba34212c5b807124eff740f90da1b6fdeb5252 from #188 and 75c107ab5950705becca41a9050696baae4129f1 from #189 have been added and 0.8.4.rc.2 has been released.

@jeremiahsnapp Please let me know if there are any remaining critical issues that need to go in 0.8.4. I've been testing this locally, but with the matrix of possible SSL configurations it would be helpful to have reports back from anyone having issues.

**Comment by carpnick** [comment] 2015-02-13 18:59
I am waiting on the --bootstrap-template

**Comment by jeremiahsnapp** [comment] 2015-02-13 19:25
@btm Thanks for 0.8.4.rc.2.

Unfortunately, every 0.8.4.rc released has failed a basic `knife bootstrap windows winrm` for me including 0.8.4.rc.2.

I am intentionally testing the added functionality using the following method on a new Vagrant VM for each command.

To test that the trusted_certs directory on the workstation gets copied to the Windows node I make sure I have a trusted_certs directory on my workstation and then run the following command.

```
knife bootstrap windows winrm 192.168.33.10 -x vagrant
```

To test that the new bootstrap options work I run the following commands.

```
knife bootstrap windows winrm 192.168.33.10 -x vagrant --node-ssl-verify-mode none

knife bootstrap windows winrm 192.168.33.10 -x vagrant --no-node-verify-api-cert
```

All of those commands failed for me until I created and used https://github.com/chef/knife-windows/pull/189

Now 0.8.4.rc.2 also failed for me but for a different reason. I've been working against the master branch which has functionality that isn't getting released in 0.8.4. Now that I'm aware of that I am working off of the new `0.8-release` branch.

The final PR that fixes 0.8.4.rc.2 is https://github.com/chef/knife-windows/pull/191
Can we please get rc.3 released with that patch?

**Comment by btm** [comment] 2015-02-13 19:49
one of those last cherry-picks pulled in some PathHelper stuff. Long story short I pulled 583a2b237a7dfa9acbed1ac9871db6803087bcc6 / https://github.com/chef/knife-windows/issues/148 into 0.8-release and pushed an 0.8.4.rc.3.

I've verified that with ```trusted_certs_dir "c:/chef/trusted_certs"``` in my knife.rb when bootstrapping a system my certificates are copied over and I get that added to my client.pem as well.

running this against a server 2008 VM:
```
knife bootstrap windows winrm 192.168.5.109 -x Administrator -P 'P@ssw0rd' -p 80 --node-verify-api-cert --node-ssl-verify-mode peer
```

is producing this in client.rb:
```
...
verify_api_cert true
ssl_verify_mode :verify_peer
trusted_certs_dir "C:/chef/trusted_certs"
```

which looks correct. the Chef 12.0.3 against hosted chef run completes fine.

**Comment by btm** [comment] 2015-02-13 19:53
@carpnick can you give an example of the behavior and command line you're expecting? You're trying to specify an alternate bootstrap template? Are you using ```knife bootstrap windows winrm``` or ```knife bootstrap windows ssh```?

**Comment by carpnick** [comment] 2015-02-13 20:07
Sure.  Used to use "--template-file" parameter:
knife windows wirnm  -x Administrator -P MyPassword --template-file c:\code\internal\bootstrap\Windows-EIS.erb -E MySampleEnvironment

Get the following error:

![image](https://cloud.githubusercontent.com/assets/6966179/6194381/e3bf28c2-b391-11e4-88c1-bae94aefb088.png)


Not sure if this is fixed by your latest change.  Wasnt sure if I should wait until you implement the new parameter: --bootstrap-template

**Comment by btm** [comment] 2015-02-13 20:14
@carpnick you should try out knife-windows 0.8.4.rc.3, it definitely has that error fixed and I've tested that the ```knife bootstrap windows winrm --template-file``` option works there.

I've researched and summarized the --bootstrap-template / --distro / --template-file situation over here: https://github.com/chef/knife-windows/issues/192

Since I think we have a workaround, we'll get that all fixed for knife-windows 1.0.0 in a couple weeks as next week my team is busy doing a chef release and we'll be starting to test knife-windows/master more after.

**Comment by jeremiahsnapp** [comment] 2015-02-13 20:16
@btm thanks for 0.8.4.rc.3. I tested it too and it works for me.

**Comment by btm** [comment] 2015-02-17 16:00
I haven't heard any more since one way or the other, so I'm presuming this RC is good for all and I'm going to ship 0.8.4 today.

**Comment by btm** [comment] 2015-03-04 16:11
Alright, woo. I'm going to close this now. I'm not aware of any remaining differences that don't have issues filed, e.g. https://github.com/chef/knife-windows/issues/192, https://github.com/chef/knife-windows/issues/193. If anyone knows of remaining issues please file a specific issue for it.

**Closed by btm** 2015-03-04 16:11 UTC

**Comment by carpnick** [comment] 2015-03-04 16:14
Confirmed that  --template-file now works with .8.4
