### ISSUE TITLE
Knife winrm times out with HTTP 500 after 30 minutes

### ISSUE THREAD

**Issue by justinrstout** [chef/knife-windows#172] opened 2015-02-06 18:38 UTC
I have a windows machine with WinRM configured as follows: 

```
C:\Users\Administrator>winrm get winrm/config
Config
    MaxEnvelopeSizekb = 500
    MaxTimeoutms = 14400000
    MaxBatchItems = 32000
    MaxProviderRequests = 4294967295
    Client
        NetworkDelayms = 5000
        URLPrefix = wsman
        AllowUnencrypted = false
        Auth
            Basic = true
            Digest = true
            Kerberos = true
            Negotiate = true
            Certificate = true
            CredSSP = false
        DefaultPorts
            HTTP = 5985
            HTTPS = 5986
        TrustedHosts
    Service
        RootSDDL = O:NSG:BAD:P(A;;GA;;;BA)(A;;GR;;;IU)S:P(AU;FA;GA;;;WD)(AU;SA;GXGW;;;WD)
        MaxConcurrentOperations = 4294967295
        MaxConcurrentOperationsPerUser = 1500
        EnumerationTimeoutms = 240000
        MaxConnections = 300
        MaxPacketRetrievalTimeSeconds = 120
        AllowUnencrypted = true
        Auth
            Basic = true
            Kerberos = true
            Negotiate = true
            Certificate = false
            CredSSP = false
            CbtHardeningLevel = Relaxed
        DefaultPorts
            HTTP = 5985
            HTTPS = 5986
        IPv4Filter = *
        IPv6Filter = *
        EnableCompatibilityHttpListener = false
        EnableCompatibilityHttpsListener = false
        CertificateThumbprint
        AllowRemoteAccess = true
    Winrs
        AllowRemoteShellAccess = true
        IdleTimeout = 14400000
        MaxConcurrentUsers = 10
        MaxShellRunTime = 2147483647
        MaxProcessesPerShell = 25
        MaxMemoryPerShellMB = 4096
        MaxShellsPerUser = 30
```

When I run this command against that machine:

`knife winrm -m 10.xxx.xxx.xxx -x username -P password "powershell -Command \"Start-Sleep -s 3600\""`

Then after exactly 30 minutes I get this error:

`ERROR: WinRM::WinRMHTTPTransportError: Bad HTTP response returned from server (500).`

When I run this command against the same machine:

`winrs -r:10.xxx.xxx.xxx -u:username -p:password "powershell -command Start-Sleep -s 3600"`

Then the command runs the full hour.

**Comment by adamedx** [comment] 2015-02-09 23:32
Is the default 30 minutes? The behavior would be consistent with Windows somehow ignoring configured settings in the knife case and going with the default, though there is no particular reason why I would expect that behavior.

One possibility here is security context -- in the scenario above, knife winrm is doing basic auth. The winrs tool however is doing negotiate (the default). You could try forcing knife-winrm to try to do negotiate  by using a name format of '.\username'. The latest master branch of knife-windows also has explicit control of the auth protocol.

So a possible difference is that due to the way auth is done, Windows is picking up default settings for WinRM, though against that's just a theory. Otherwise, there should be no difference in the two commands.

**Comment by justinrstout** [comment] 2015-02-10 20:17
Yes, 30 minutes is the default for IdleTimeout and MaxTimeoutms. I tried using the ".\username" format, but got the same error.

**Comment by adamedx** [comment] 2015-02-11 16:04
This sounds similar to https://tickets.opscode.com/browse/KNIFE-208, which was addressed with a Microsoft Patch: http://support.microsoft.com/kb/2842230. In that bug, Windows would ignore non-default WinRM settings. The difference is that it seemed to do it always, not depending on what tools you used.
Are you using PowerShell 3? I think the issue is fixed in PowerShell 4 and higher (which redist the WinRM stack).

**Comment by carpnick** [comment] 2015-02-11 17:50
This is the [default timeout](https://github.com/chef/knife-windows/blob/master/lib/chef/knife/winrm.rb#L187) in knife-windows currently.  See PR to bring it to the CLI to be parameterized: #186

**Comment by justinrstout** [comment] 2015-02-16 17:13
Manually increasing `session_opts[:operation_timeout]` fixes the problem for me.

**Comment by cheeseplus** [comment] 2018-01-05 20:08
Closing old resolved issues, please open a new issue with current versions of the software if experiencing the same behaviour.

**Closed by cheeseplus** 2018-01-05 20:08 UTC
