### ISSUE TITLE
ignor_install

### ISSUE THREAD

**Issue by athingisathing** [chef/knife-windows#263] opened 2015-07-10 22:17 UTC
We need the ability to ignor the install and just bootstrap the server. We install chef separately  and would like to have this added.

In our linux bootstrap we use a hack called --bootstrap-install-command but for some reason we cant use that in the knife windows.

Also it is defualting to the internet for pem files and chef org's i would remove that also..

**Comment by adamedx** [comment] 2015-07-14 22:49
@NimishaS, can you take a look at this issue? It's not clear to me if this is a regression, or missing functionality supported when bootstrapping linux nodes.

I'm guessing the issue is that this feature was not implemented in knife-windows 1.0.0: https://github.com/chef/chef/blob/master/lib/chef/knife/bootstrap.rb#L173.

If so, we should go ahead and add the feature, and also document issues for any other missing bootstrap commands

**Comment by athingisathing** [comment] 2015-07-15 00:14
The way to do it Unix is still a hack... :)

We are writing an option into knife windows ignor_install for now

**Comment by NimishaS** [comment] 2015-07-15 07:29
@adamedx, @btm, @ksubrama , we had a discussion on hipchat about adding Chef 12 options in `knife-windows` and decided to drop `--bootstrap-install-command` option since we already have `msi-url` option. Here is the PR: https://github.com/chef/knife-windows/issues/245
Card for the same: https://chef.leankit.com/Boards/View/101745940/209174004. Please go through the comments.

Should we add `ignor_install` option then?

**Comment by adamedx** [comment] 2015-07-15 14:16
@athingisathing, can you elaborate on your use case? It sounds like the following:

1. Your images boot up with chef-client already installed and pem files availalble
2. You'd like to execute a bootstrap command using that installed chef-client and the pem files

Is that correct @athingisathing? If so, could you just use the `knife winrm` command rather than `knife bootstrap`? Something like

`knife winrm -m computername -x user -P somepass 'chef-client -r yourrunlist'`

That would bootstrap the node if you have chef-client installed already.

**Comment by athingisathing** [comment] 2015-07-15 18:53
We have two processes for various ENTeprize BS.... Also we run all this on
the server as we bring it up in our cloud.

The first is we install chef.

This works just fine...

The second is we bootstrap to an org.

This will actually bootstrap the server to an org only with validatorless
bootstraping....  If this is possible with the above command  we know above
with no password and just the user pem key then great. This may be that my
guy working on this issue did not re think what we could do... fixing the
symptom not the disease. We had been  "" boot strapping when now we could
just strait up add the server to the org... but I'm not sure that does
everything we want.  Remember we have to do all of this from the server
itself adn then clean up the artifacts.

though more to the point and with all our BS out of the way, i think the
boot straping would detect if chef is installed and optionally at a needed
version or higher and just move on you would have much more stable quicker
code. no flag needed

**Comment by athingisathing** [comment] 2015-07-15 20:36
our usecase

simplified:

install chef
add to org
add env
add role
maybe run chef-client

so if chef is installed
   if installed  check fo version
   if version sent ensure at or above version
   if not re install

Add to an org
   remove from any org currently registered in. (we do this by setting env
settings every time its registered to know who you were registered to and
then de registering them)
   Add to org
   change ENV settings
   re register.

we user bootstrap because we can pass env nd role and complete the above
all in one command.

maybe on run of chef-client becuase we current set everything up but dont
run until client tells us.

we are working on a bootstrap script much like your omnibuss install.sh
script that will generically do all this to a default org and then allow
user to pass in variables to abstract all this.  our current blocker is
they above fore windows... in lunx we are done, other then we are working
on a way to sign or encrypt the pem key for the user that is admin in the
org.'

sorry for not adding this needed to re visit the details.




On Wed, Jul 15, 2015 at 11:53 AM, Joshua Schipper <joshua.schipper@gmail.com

**Comment by NimishaS** [comment] 2015-07-16 10:09
@athingisathing , you can also write custom bootstrap template and pass it to `--bootstrap-template` option.

**Comment by adamedx** [comment] 2015-07-17 05:40
@NimishaS I think from a parity standpoint, we should support the --install-command feature so there's no difference between knife and knife-windows. We should validate that the validatorless bootstrap case works manually since I believe that is part of this use case.

@athingisathing, can you tell us two things:

1. What is the command line you are using to bootstrap the node in the Linux case?
2. I think you already have a pem file on the system -- how do you prevent knife from sending one "over the Internet" in the Linux case that works for you?

**Comment by athingisathing** [comment] 2015-07-17 18:06
Tyler Fitch has the command and stack trace from my attempt to use
templates also....

Lets meet on this and then repost our findings so we can be clear for
people on watching the issue. I dont have teh focus to do what i should so
maybe a meeting would get me to focus and you what you need :)

Reach out to tyler and lets contect the dots :)

**Comment by adamedx** [comment] 2015-08-31 16:34
Just to be clear, the fix here should be parity with the standard `knife bootstrap` command.

**Comment by Aliasgar16** [comment] 2015-09-02 11:46
Please refer PR https://github.com/chef/knife-windows/pull/275

Thanks

**Comment by btm** [comment] 2015-10-06 19:23
This was fixed in #275 and released recently in knife-windows 1.0.0. See the [release notes](https://github.com/chef/knife-windows/blob/master/RELEASE_NOTES.md#features-added-in-knife-windows-100) for more information.

**Closed by btm** 2015-10-06 19:23 UTC
