### ISSUE TITLE
undefined method `gsub' for false:FalseClass when running "knife bootstrap windows"

### ISSUE THREAD

**Issue by aarsan** [chef/knife-windows#221] opened 2015-04-30 22:09 UTC
ERROR: knife encountered an unexpected error
This may be a bug in the 'bootstrap windows winrm' knife command or plugin
Please collect the output of this command with the `-VV` option before filing a bug report.
Exception: NoMethodError: undefined method `gsub' for false:FalseClass

and here is the output of -VV

DEBUG: :session => :init
DEBUG: :relay_to_servers => echo . & echo Response received.
DEBUG: :relayed => some-server.cloudapp.net
DEBUG: some-server.cloudapp.net => :run_command
DEBUG: some-server.cloudapp.net[9D10C3A8-3067-42D6-98F1-427A906DFB7A] => :shell_open
DEBUG: some-server.cloudapp.net[9D10C3A8-3067-42D6-98F1-427A906DFB7A] => :run_command[echo . & echo Response received.]
DEBUG: :relay_output_from_backend => ["some-server.cloudapp.net", ". \r\n"]some-server.cloudapp.net .
DEBUG: :relay_output_from_backend => ["some-server.cloudapp.net", "Response received.\r\n"]some-server.cloudapp.net Response received.
DEBUG: some-server.cloudapp.net[9D10C3A8-3067-42D6-98F1-427A906DFB7A] => :command_cleanup[echo . & echo Response receive.]
DEBUG: some-server.cloudapp.net[9D10C3A8-3067-42D6-98F1-427A906DFB7A] => :shell_close
DEBUG: :command_complete => some-server.cloudapp.net with return code 0
DEBUG: command complete on some-server.cloudapp.net
DEBUG: command complete on All Servers
DEBUG: Exit code found: 0
DEBUG: :unbind => :connection
DEBUG: some-server.cloudapp.net => :unbind
DEBUG: :unbind_backend => some-server.cloudapp.net
DEBUG: :session => :close
Remote node responded after 0.7 minutes.
Bootstrapping Chef on some-server.cloudapp.net
DEBUG: Looking for bootstrap template in C:/Users/aa10187/.chefdk/gem/ruby/2.1.0/gems/knife-windows-0.8.4/lib/chef/knif/bootstrap
DEBUG: Found bootstrap template in C:/Users/aa10187/.chefdk/gem/ruby/2.1.0/gems/knife-windows-0.8.4/lib/chef/knife/boottrap
ERROR: knife encountered an unexpected error
This may be a bug in the 'bootstrap windows winrm' knife command or plugin
Please collect the output of this command with the `-VV` option before filing a bug report.
Exception: NoMethodError: undefined method `gsub' for false:FalseClass

**Comment by ac-rmenezes** [comment] 2015-05-07 03:53
Bump.

**Comment by duncan-bayne** [comment] 2015-05-07 04:34
:+1: ... I'm experiencing the same problem:

```
knife-solo (0.4.2)
knife-windows (0.8.4)
chef (12.3.0)
```

**Comment by Vasu1105** [comment] 2015-05-07 04:46
@aarsan are you trying validatorless bootstrap with knife bootstrap windows winrm ? If yes validatorless bootstrap is not yet supported on knife-windows winrm bootstrap and because of this it might be throwing the error. So define validation_client_name and validation_key in knife.rb and try. We are working on this feature for knife-windows.

**Comment by ac-rmenezes** [comment] 2015-05-07 11:43
@aarsan, @Duncan, if you guys are using chef starter (like myself), you may
just be running the bootstrap outside chef-repo directory. Just worked here.

On Thu, May 7, 2015 at 1:46 AM, Vasundhara Jagdale <notifications@github.com
> wrote:

> @aarsan <https://github.com/aarsan> are you trying validatorless
> bootstrap with knife bootstrap windows winrm ? If yes validatorless
> bootstrap is not yet supported on knife-windows winrm bootstrap and because
> of this it might be throwing the error. So define validation_client_name
> and validation_key in knife.rb and try. We are working on this feature for
> knife-windows.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/chef/knife-windows/issues/221#issuecomment-99715961>.
>



-- 
*Rafael de Menezes*
Avenue Code | www.avenuecode.com
R.Pernambuco, 1000, 8 andar | Savassi, Belo Horizonte
*Tel*: 31-2516-1448 *Cel:* 31-9943-0210
*E-mail*: rmenezes*@avenuecode.com <http://avenuecode.com/>*  | *Skype*:
demenezesrafael

<http://www.jobs.net/jobs/avenuecode/en-us/>

**Comment by btm** [comment] 2015-05-27 21:29
Duplicate of https://github.com/chef/knife-windows/issues/227

**Closed by btm** 2015-05-27 21:29 UTC
