### ISSUE TITLE
bootstrap fails with a 500 error when allowunencrypted is true

### ISSUE THREAD

**Issue by btm** [chef/knife-windows#210] opened 2015-03-18 21:46 UTC
Now that we've bumped up to winrm 1.3, I think I'm seeing https://github.com/chef/winrm-s/issues/13 again.

```
PS C:\Users\btm_000\Documents\GitHub\knife-windows> knife bootstrap windows winrm 192.168.5.109 -x Administrator -P 'P@ssw0rd' -p 80

Waiting for remote response before bootstrap.......................ERROR: No response received from remote node after 1.92 minutes, giving up.
ERROR: WinRM::WinRMHTTPTransportError: Unable to parse WinRM response: #<ArgumentError: invalid byte sequence in UTF-8>
C:/opscode/chef/embedded/lib/ruby/1.9.1/rexml/source.rb:210:in `match'
C:/opscode/chef/embedded/lib/ruby/1.9.1/rexml/source.rb:210:in `match'
C:/opscode/chef/embedded/lib/ruby/1.9.1/rexml/parsers/baseparser.rb:202:in `pull_event'
C:/opscode/chef/embedded/lib/ruby/1.9.1/rexml/parsers/baseparser.rb:183:in `pull'
C:/opscode/chef/embedded/lib/ruby/1.9.1/rexml/parsers/treeparser.rb:22:in `parse'
C:/opscode/chef/embedded/lib/ruby/1.9.1/rexml/document.rb:245:in `build'
C:/opscode/chef/embedded/lib/ruby/1.9.1/rexml/document.rb:43:in `initialize'
C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/winrm-1.3.0/lib/winrm/http/response_handler.rb:42:in `new'
C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/winrm-1.3.0/lib/winrm/http/response_handler.rb:42:in `response_xml'
C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/winrm-1.3.0/lib/winrm/http/response_handler.rb:61:in `raise_if_wsman_fault'
C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/winrm-1.3.0/lib/winrm/http/response_handler.rb:51:in `raise_if_error'
C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/winrm-1.3.0/lib/winrm/http/response_handler.rb:35:in `parse_to_xml'
C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/winrm-1.3.0/lib/winrm/http/transport.rb:50:in `send_request'
C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/winrm-1.3.0/lib/winrm/winrm_service.rb:421:in `send_message'
C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/winrm-1.3.0/lib/winrm/winrm_service.rb:126:in `open_shell'
C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/knife-windows-1.0.0.dev.0/lib/chef/knife/winrm_session.rb:44:in `relay_command'
C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/knife-windows-1.0.0.dev.0/lib/chef/knife/winrm.rb:92:in `block in relay_winrm_command'
C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/knife-windows-1.0.0.dev.0/lib/chef/knife/winrm.rb:91:in `each'
C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/knife-windows-1.0.0.dev.0/lib/chef/knife/winrm.rb:91:in `relay_winrm_command'
C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/knife-windows-1.0.0.dev.0/lib/chef/knife/winrm.rb:60:in `execute_remote_command'
C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/knife-windows-1.0.0.dev.0/lib/chef/knife/winrm.rb:51:in `run'
C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/knife-windows-1.0.0.dev.0/lib/chef/knife/bootstrap_windows_winrm.rb:63:in `run_command'
C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/knife-windows-1.0.0.dev.0/lib/chef/knife/bootstrap_windows_winrm.rb:80:in `wait_for_remote_response'
C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/knife-windows-1.0.0.dev.0/lib/chef/knife/bootstrap_windows_base.rb:172:in `bootstrap'
C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/knife-windows-1.0.0.dev.0/lib/chef/knife/bootstrap_windows_winrm.rb:40:in `run'
C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.18.6-x86-mingw32/lib/chef/knife.rb:493:in `run_with_pretty_exceptions'
C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.18.6-x86-mingw32/lib/chef/knife.rb:174:in `run'
C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.18.6-x86-mingw32/lib/chef/application/knife.rb:139:in `run'
C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.18.6-x86-mingw32/bin/knife:25:in `<top (required)>'
C:/opscode/chef/bin/knife:23:in `load'
C:/opscode/chef/bin/knife:23:in `<main>'
...
invalid byte sequence in UTF-8
Line: 11
Position: 1192
Last 80 unconsumed characters:
 Or (500).ype: application/HTTP-SPNEGO-session-encrypted
```

knife wsman test is able to connect though:
```
> knife wsman test -m 192.168.5.109 -p 80
Connected successfully to 192.168.5.109 at http://192.168.5.109:80/wsman.
```

Running this on the target node fixes the error:
```
C:\Users\Administrator>winrm set winrm/config/service @{AllowUnencrypted="false"}
```

We need to provide more useful output in this case, especially since we've been telling peopel to set up there systems this way for a long time.

**Comment by adamedx** [comment] 2015-04-06 16:17
So does this repro only on 2008r2 and not on 2012? Also, does this go away if we downgrade to an old winrm gem?
It's quite possible the winrm-s monkeypatch doesn't work in some cases here.
Since this is Windows to Windows, I would expect this to work out of the box.

**Comment by btm** [comment] 2015-04-06 19:00
@adamedx, @smurawski thought he knew what was going on, so I haven't tried to replicated it in more situations, but he looked at it live with me and was able to replicate it himself, I think against a newer target machine. He was working on a fix/better error.

**Comment by siddheshwar-more** [comment] 2015-04-09 14:20
@btm @adamedx 

I've tried following things-

I've used ***knife-windows*** master branch and ***WinRM*** master branch.
with this knife-windows patch https://gist.github.com/siddheshwar-more/4643438027b0884f4d3d
 
**Note-** If we don't use above patch it will give you command too long error( for bootstrap_windows_base.rb change) and bootstrap: (echo.echo.) was unexpected at this time(for core/windows_bootstrap_context.rb file change) . 

By using above code did knife bootstrap windows winrm ( on 2008r2 and 2012 platform)

1. With basic authentication protocol i.e ***--winrm-authentication-protocol basic*** and on remote server allowunencrypted is true. I'm able to bootstrap windows node successfully .
Refer logs- https://gist.github.com/siddheshwar-more/0a06c046eb8008c3beb4  

2. With negotiate authentication protocol i.e ***--winrm-authentication-protocol negotiate*** and on remote server allowunencrypted is false. I got http error code ***400*** and bootstrap failed .
Refer logs- https://gist.github.com/siddheshwar-more/a431d9fbc1c481211f0d

**Comment by btm** [comment] 2015-04-14 15:54
The echo.echo issue was fixed upstream in winrm by https://github.com/chef/knife-windows/issues/211. The fix was released in v1.3.1.

@siddheshwar-more as we discussed on Hipchat, we're confusing ourselves by discussing many issues on one ticket. Please try to replicate the "command too long" error again, and open a new issue for it with detailed information specific to that error so we can work on it there.

@smurawski is working on a fix for the original issue where we don't provide a good error message (or fall back to something else) if negotiate fails because of an allowunencrypted setting.

**Comment by btm** [comment] 2015-04-14 16:06
@smurawski https://github.com/chef/knife-windows/issues/216 reminded me we used to raise a ```Hint: Please check winrm configuration 'winrm get winrm/config/service' AllowUnencrypted flag on remote server.``` error when we got a 401, and we're not seeing that right now.

**Comment by siddheshwar-more** [comment] 2015-04-15 16:07
@btm 
It tried knife-windows master version with winrm 1.3.1. Here's my result-
1. echo echo and cmd line to long related issues is fixed in winrm latest release

2.  got HTTP Error 400 with --winrm-authentication-protocol negotiate
seems its due to WinRM https://github.com/WinRb/WinRM/pull/134

For #2 created https://github.com/chef/knife-windows/issues/218

**Comment by adamedx** [comment] 2015-04-15 16:09
Is the issue with negotiate a regression from 0.8.4? Because if it isn't, it shouldn't block us from shipping this.

**Comment by adamedx** [comment] 2015-04-15 16:19
never mind, it sounds like it's a regression according to @siddheshwar-more, and also we're changing the default to negotiate protocol in knife-windows, so even if it weren't a regression, it will feel like one because of different defaults.

**Comment by btm** [comment] 2015-04-15 17:33
@adamedx the most recent comment by @siddheshwar-more isn't the original bug. When we talked yesterday, we realized that we were talking about many bugs on this one ticket. Since this ticket was filed we switched to winrm 1.3+ which has introduced a bunch of new bugs / behaviors that we're trying to resolve. In @siddheshwar-more previous comment (https://github.com/chef/knife-windows/issues/210#issuecomment-91246044) he mentioned seeing two issues: 1) "command too long" error and 2) echo.echo. The second one we previously filed as https://github.com/chef/knife-windows/issues/211 and has been resolved. I asked him to see if he could still replicate the "command too long" error and to file a separate issue if he could. From his comment, he couldn't, so we're considering that one resolved by https://github.com/chef/knife-windows/issues/211 as well.

The regression for this particular issue is that on 0.8.0 we had an error when you got negotiate (magically) and you had allowunencrypted set to false. We raised okay error, we just didn't tell you what was wrong, which lead to https://github.com/chef/knife-windows/issues/108. We improved that with https://github.com/chef/knife-windows/pull/109 by telling you that we were giving you negotiate at least when we did that to you magically. That went out in 0.8.2.

In 0.8.4, I can run: ```knife bootstrap windows winrm 192.168.5.105 -x Administrator -P 'P@ssw0rd'``` fine with AllowUnencrypted=true because I'm not using a domain user and not being given negotiate auth.

If I run 0.8.4 with ```knife bootstrap windows winrm 192.168.5.105 -x .\Administrator -P 'P@ssw0rd'```  then I eventually get the ```ERROR: RuntimeError: Error: Unencrypted communication not supported. Please check winrm configuration winrm/config/service AllowUnencrypted flag.``` error.

Since negotiate is now the default (without the .\Administrator hack) I should have gotten this error above at least (...Unencrypted communication not supported...) but I didn't get anything.

It's possible our code is still correct and we're hitting an unexpected winrm gem change, but I'm waiting to hear back from @smurawski on his findings first.

**Comment by smurawski** [comment] 2015-04-18 18:19
I can't replicate this again.  We definitely hit the failure to leverage negotiate auth, but we error quickly now.  If we look at how winrs works, if negotiate is available, the service will try to use it regardless of the state of "AllowUnencrypted".  If "AllowUnencyrpted" is set, the winrm service can return unencrypted payloads, but this is a bug in winrm-s not knife-windows.  
I filed https://github.com/chef/winrm-s/issues/26 to track it.

**Comment by btm** [comment] 2015-04-20 19:21
@smurawski the error may have been fixed by https://github.com/chef/knife-windows/issues/218 / https://github.com/chef/winrm-s/pull/25

**Comment by smurawski** [comment] 2015-04-29 18:40
We now emit 
ERROR: RuntimeError: Error: Unencrypted communication not supported. Please check winrm configuration winrm/config/service AllowUnencrypted flag.
and quickly fail.

**Closed by smurawski** 2015-04-29 18:40 UTC
